import type { NutritionFood } from './nutritionTypes'

export const FOOD_NUTRITION_DATABASE: NutritionFood[] = [
  {
    id: 'idli',
    name: 'Idli',
    category: 'Grains & Staples',
    servingSize: '2 pieces',
    calories: 180,
    protein: 6,
    carbohydrates: 34,
    fat: 1,
    fiber: 4,
    sugar: 1,
    sodium: 140,
    nutritionSource: 'USDA / Indian food composition references',
    verified: false,
  },
  {
    id: 'dosa',
    name: 'Dosa',
    category: 'Grains & Staples',
    servingSize: '1 medium dosa',
    calories: 210,
    protein: 5,
    carbohydrates: 31,
    fat: 6,
    fiber: 3,
    sugar: 2,
    sodium: 220,
    nutritionSource: 'USDA / Indian food composition references',
    verified: false,
  },
  {
    id: 'rice',
    name: 'Rice',
    category: 'Grains & Staples',
    servingSize: '1 cup cooked',
    calories: 205,
    protein: 4,
    carbohydrates: 45,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0,
    sodium: 1,
    nutritionSource: 'USDA / Indian food composition references',
    verified: false,
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    servingSize: '1 medium',
    calories: 105,
    protein: 1.3,
    carbohydrates: 27,
    fat: 0.3,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'curd',
    name: 'Curd',
    category: 'Dairy',
    servingSize: '1 cup',
    calories: 150,
    protein: 10,
    carbohydrates: 8,
    fat: 8,
    fiber: 0,
    sugar: 7,
    sodium: 70,
    nutritionSource: 'USDA / standard yogurt values',
    verified: false,
  },
  {
    id: 'paneer',
    name: 'Paneer',
    category: 'Dairy',
    servingSize: '100 g',
    calories: 265,
    protein: 18,
    carbohydrates: 6,
    fat: 20,
    fiber: 0,
    sugar: 3,
    sodium: 470,
    nutritionSource: 'USDA / Indian food composition references',
    verified: false,
  },
  {
    id: 'egg',
    name: 'Egg',
    category: 'Eggs',
    servingSize: '1 large egg',
    calories: 72,
    protein: 6,
    carbohydrates: 0.4,
    fat: 5,
    fiber: 0,
    sugar: 0.4,
    sodium: 70,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'chicken',
    name: 'Chicken',
    category: 'Meat & Poultry',
    servingSize: '100 g cooked',
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'fish',
    name: 'Fish',
    category: 'Fish',
    servingSize: '100 g cooked',
    calories: 206,
    protein: 22,
    carbohydrates: 0,
    fat: 12,
    fiber: 0,
    sugar: 0,
    sodium: 93,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'vegetables',
    name: 'Mixed Vegetables',
    category: 'Vegetables',
    servingSize: '1 cup',
    calories: 50,
    protein: 2,
    carbohydrates: 10,
    fat: 0.3,
    fiber: 4,
    sugar: 5,
    sodium: 40,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'dal',
    name: 'Dal',
    category: 'Legumes',
    servingSize: '1 cup cooked',
    calories: 230,
    protein: 17,
    carbohydrates: 40,
    fat: 1,
    fiber: 15,
    sugar: 2,
    sodium: 15,
    nutritionSource: 'USDA / Indian food composition references',
    verified: false,
  },
  {
    id: 'oats',
    name: 'Oats',
    category: 'Grains & Staples',
    servingSize: '1 cup cooked',
    calories: 150,
    protein: 5,
    carbohydrates: 27,
    fat: 3,
    fiber: 4,
    sugar: 1,
    sodium: 0,
    nutritionSource: 'USDA food database',
    verified: false,
  },
  {
    id: 'paneer-bhurji',
    name: 'Paneer Bhurji',
    category: 'Dairy',
    servingSize: '1 serving',
    calories: 260,
    protein: 20,
    carbohydrates: 8,
    fat: 18,
    fiber: 1,
    sugar: 3,
    sodium: 420,
    nutritionSource: 'Indian household measures',
    verified: false,
  },
  {
    id: 'custom-food',
    name: 'Custom Food',
    category: 'Other',
    servingSize: '1 serving',
    calories: null,
    protein: null,
    carbohydrates: null,
    fat: null,
    fiber: null,
    sugar: null,
    sodium: null,
    nutritionSource: 'User added',
    verified: false,
  },
]

export function lookupFoodById(foodId: string): NutritionFood | undefined {
  return FOOD_NUTRITION_DATABASE.find((food) => food.id === foodId)
}

export function searchFoods(query: string): NutritionFood[] {
  const term = query.trim().toLowerCase()
  if (!term) return FOOD_NUTRITION_DATABASE.slice(0, 20)

  return FOOD_NUTRITION_DATABASE.filter((food) =>
    food.name.toLowerCase().includes(term) ||
    food.category.toLowerCase().includes(term)
  ).slice(0, 20)
}

export function normalizeFoodId(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}
